services:
  spotify-playlist-helpers:
    build: .
    volumes:
      - ./settings.env:/app/settings.env:ro
      - data:/app/data
    ports:
      - "8000:8000"
    environment:
      - USERS_DB_PATH=/app/data/users.sqlite

volumes:
  data:
