services:
  spotify-playlist-helpers:
    image: 000000000000.dkr.ecr.us-east-1.amazonaws.com/spotify-playlist-helpers:0.1-dev
    volumes:
      - ./config.json:/app/configs/config.json:ro
    ports:
      - "3000:3000"
