terraform-init-dev:
	terraform init -reconfigure -input=false -backend-config=backends/dev.s3.tfbackend

terraform-init-prod:
	terraform init -reconfigure -input=false -backend-config=backends/prod.s3.tfbackend
